// SEO data for /rent-a-car/:city static HTML generation.
// Add a new city here and re-run `npm run build`.

export const cities = [
  {
    slug: "podgorica",
    name: "Podgorica",
    lat: 42.4304, lng: 19.2594,
    priceFrom: 45,
    title: "Rent a Car Podgorica | Aerodrom TGD | Najbolje Cijene | talumarentacar.me",
    desc:  "Iznajmite auto u Podgorici po najboljim cijenama. Preuzimanje na aerodromu TGD. Taluma flotom od 60+ vozila, puno osiguranje. Odgovaramo za 5–10 minuta!",
    h1:    "Rent a Car Podgorica - Iznajmljivanje Vozila",
  },
  {
    slug: "budva",
    name: "Budva",
    lat: 42.2864, lng: 18.8400,
    priceFrom: 45,
    title: "Rent a Car Budva | Najbolje Cijene | Bez Depozita | talumarentacar.me",
    desc:  "Rent a car Budva - iznajmite auto po najboljim cijenama. Bez depozita opcija. Dostava u hotel. Taluma flotom od 60+ vozila na jednom mjestu.",
    h1:    "Rent a Car Budva - Iznajmljivanje Vozila",
  },
  {
    slug: "tivat",
    name: "Tivat",
    lat: 42.4347, lng: 18.6970,
    priceFrom: 45,
    title: "Rent a Car Tivat Aerodrom | Airport TIV | Najbolje Cijene | talumarentacar.me",
    desc:  "Rent a car Tivat aerodrom TIV. Preuzimanje na aerodromu, puno osiguranje, bez skrivenih troškova. Rezervišite sada!",
    h1:    "Rent a Car Tivat - Aerodrom TIV",
  },
  {
    slug: "kotor",
    name: "Kotor",
    lat: 42.4247, lng: 18.7712,
    priceFrom: 48,
    title: "Rent a Car Kotor | Boka Kotorska | Najbolje Cijene | talumarentacar.me",
    desc:  "Rent a car Kotor - istražite Boku Kotorsku. Dostava u Stari grad. Taluma flotom od 60+ vozila, puno osiguranje. Odgovaramo za 30min!",
    h1:    "Rent a Car Kotor - Iznajmljivanje Vozila",
  },
  {
    slug: "bar",
    name: "Bar",
    lat: 42.0936, lng: 19.0950,
    priceFrom: 45,
    title: "Rent a Car Bar Montenegro | Najbolje Cijene | talumarentacar.me",
    desc:  "Rent a car Bar Crna Gora - južno primorje, Ulcinj, Stari Bar. Puno osiguranje, bez skrivenih troškova.",
    h1:    "Rent a Car Bar - Iznajmljivanje Vozila",
  },
  {
    slug: "herceg-novi",
    name: "Herceg Novi",
    lat: 42.4531, lng: 18.5375,
    priceFrom: 45,
    title: "Rent a Car Herceg Novi | Boka Kotorska | talumarentacar.me",
    desc:  "Rent a car Herceg Novi - blizu Dubrovnika. Puno osiguranje, dostava u hotel. Odgovaramo za 5–10 minuta!",
    h1:    "Rent a Car Herceg Novi",
  },
  {
    slug: "ulcinj",
    name: "Ulcinj",
    lat: 41.9293, lng: 19.2245,
    priceFrom: 45,
    title: "Rent a Car Ulcinj | Velika Plaža | Najbolje Cijene | talumarentacar.me",
    desc:  "Rent a car Ulcinj - Velika Plaža, Ada Bojana. Puno osiguranje, povoljne cijene od Taluma flotom od 60+ vozila.",
    h1:    "Rent a Car Ulcinj",
  },
  {
    slug: "niksic",
    name: "Nikšić",
    lat: 42.7731, lng: 18.9483,
    priceFrom: 40,
    title: "Rent a Car Nikšić | Durmitor | Najbolje Cijene | talumarentacar.me",
    desc:  "Rent a car Nikšić - polazna tačka za Durmitor i sjever CG. Puno osiguranje, lokalne agencije.",
    h1:    "Rent a Car Nikšić",
  },
  {
    slug: "petrovac",
    name: "Petrovac",
    lat: 42.2050, lng: 18.9461,
    priceFrom: 45,
    title: "Rent a Car Petrovac | Crnogorsko Primorje | talumarentacar.me",
    desc:  "Rent a car Petrovac - mirno primorje, porodični odmor. Puno osiguranje, dostava u hotel.",
    h1:    "Rent a Car Petrovac",
  },
  {
    slug: "sveti-stefan",
    name: "Sveti Stefan",
    lat: 42.2563, lng: 18.8917,
    priceFrom: 48,
    title: "Rent a Car Sveti Stefan | Luksuzna Obala | talumarentacar.me",
    desc:  "Rent a car Sveti Stefan - luksuzna obala Crne Gore. Dostava u hotel, puno osiguranje, Taluma flotom od 60+ vozila.",
    h1:    "Rent a Car Sveti Stefan",
  },
  {
    slug: "becici",
    name: "Bečići",
    lat: 42.2733, lng: 18.8542,
    priceFrom: 45,
    title: "Rent a Car Bečići | Plaža Bečići | talumarentacar.me",
    desc:  "Rent a car Bečići - popularna plaža, blizu Budve. Dostava u hotel, puno osiguranje.",
    h1:    "Rent a Car Bečići",
  },
  {
    slug: "zabljak",
    name: "Žabljak",
    lat: 43.1556, lng: 19.1228,
    priceFrom: 45,
    title: "Rent a Car Žabljak | Durmitor | SUV & 4x4 | talumarentacar.me",
    desc:  "Rent a car Žabljak Durmitor - SUV i 4x4 vozila za planinu. Lokalne agencije, puno osiguranje.",
    h1:    "Rent a Car Žabljak",
  },
  {
    slug: "cetinje",
    name: "Cetinje",
    lat: 42.3911, lng: 18.9239,
    priceFrom: 42,
    title: "Rent a Car Cetinje | Prijestonica CG | talumarentacar.me",
    desc:  "Rent a car Cetinje - prijestonica Crne Gore. Između Podgorice i mora. Puno osiguranje, lokalne agencije.",
    h1:    "Rent a Car Cetinje",
  },
  {
    slug: "berane",
    name: "Berane",
    lat: 42.8419, lng: 19.8736,
    priceFrom: 40,
    title: "Rent a Car Berane | Sjever CG | talumarentacar.me",
    desc:  "Rent a car Berane - sjever Crne Gore, Bjelasica, Biogradsko jezero. Lokalne agencije, povoljne cijene.",
    h1:    "Rent a Car Berane",
  },
  {
    slug: "bijelo-polje",
    name: "Bijelo Polje",
    lat: 43.0353, lng: 19.7475,
    priceFrom: 40,
    title: "Rent a Car Bijelo Polje | Sjever CG | talumarentacar.me",
    desc:  "Rent a car Bijelo Polje - na putu ka Srbiji. Lokalne agencije, povoljne cijene, puno osiguranje.",
    h1:    "Rent a Car Bijelo Polje",
  },
  {
    slug: "pljevlja",
    name: "Pljevlja",
    lat: 43.3567, lng: 19.3583,
    priceFrom: 40,
    title: "Rent a Car Pljevlja | Tara & Durmitor | talumarentacar.me",
    desc:  "Rent a car Pljevlja - sjever CG, Tara, Durmitor. Lokalne agencije, povoljne cijene.",
    h1:    "Rent a Car Pljevlja",
  },
];
